### PR TITLE
386 folder listing

### PR DESCRIPTION
**Pull request by fredvd**
block usage of skin_folder folder_listing in the site. (barceloneta uses it's own templates from p.a.contenttypes)

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by mattss** [comment]
Test this please

**Comment by gyst** [comment]
Should lock down all of these
app@freya(ploneintranet):app$ ls parts/omelette/Products/CMFPlone/skins/plone_content/
folder_full_view_item.pt      folder_listing.pt           folder_summary_view.pt.metadata
folder_full_view.pt           folder_listing.pt.metadata  folder_tabular_view.pt
folder_full_view.pt.metadata  folder_summary_view.pt      folder_tabular_view.pt.metadata

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by gyst** [comment]
Test this please

**Comment by gyst** [comment]
Test this please

**Pull request merged**
