### PR TITLE
Remove ploneintranet.workspace.workspacefolder from allowed_content_t…

### PR DESCRIPTION
**Pull request by ale-rt**
…ypes

### CODE REVIEW

**Comment by ale-rt** [comment]
Jenkins test this please

**Comment by ale-rt** [comment]
Jenkins test this please

**Comment by ale-rt** [comment]
This is work in progress at the moment, if anybody wants to continue fixing tests is welcome.
I will not be able to work on this for a while.

**Comment by ale-rt** [comment]
While watching motorcycles on tv I found time to fix the tests :)

**Comment by pilz** [comment]
sisyphos comes to mind ;)

**Pull request merged**
