### PR TITLE
update_todos_state: perform transition as temporary Editor

### PR DESCRIPTION
**Pull request by cillianderoiste**
This allows Todo transitions to be protected by the Editor role, and
also for the workflow state to be set to Open or Planned as
appropriate.

Without this change it is possible for a user to perform a transition on
a Case which puts it into a state where that user no longer has the
permissions to edit Todo items. The event handler will then try to
update the workflow state of Todo items e.g. from Planned to Open and
this will fail, which will cause the whole transaction to fail.

### CODE REVIEW

**Comment by cillianderoiste** [comment]
retest this please

**Comment by gyst** [comment]
Putting this PR on hold since it has no test coverage, and testing it manually breaks

Module ploneintranet.workspace.adapters, line 292, in metromap_sequence
NameError: global name 'available_transition_ids' is not defined

@cillianderoiste Can you please NOT disable your pre-commit hooks?

/app/src/ploneintranet/workspace/adapters.py:292:45: F821 undefined name 'available_transition_ids'

**Comment by gyst** [comment]
I will work on #758 and #517 and #462 today.

**Comment by cillianderoiste** [comment]
@gyst sorry about the code-analysis failures, the pre-commit hooks never worked for me ... I must fix that.

**Comment by gyst** [comment]
Superseded by #773, closing.

**Pull request closed without merging**
