### PR TITLE
Check for can_edit before showing the delete button

### PR DESCRIPTION
**Pull request by fredvd**

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Add to whitelist.
Jenkins please test this.

**Comment by gyst** [comment]
test this please test this

**Comment by gyst** [comment]
@fredvd please add a robot test for this

**Comment by gyst** [comment]
Jenkins please test this

**Comment by gyst** [comment]
Jenkins test this please

**Comment by gyst** [comment]
Fixed #422

**Pull request merged**
