### PR TITLE
Delete confirmation

### PR DESCRIPTION
**Pull request by reinhardt**
override delete_confirmation with a template conforming to prototype

### CODE REVIEW

**Comment by pilz** [comment]
merged master

**Comment by reinhardt** [comment]
Pushed fixes, awaiting new test result.

**Comment by gyst** [comment]
Is this PR duplicated in #624?

**Comment by pysailor** [comment]
@reinhardt I merged master into this branch again. In light of #650, is this PR still valid?

**Comment by ale-rt** [comment]
After having a proper template:
- https://github.com/ploneintranet/ploneintranet/pull/650
  I have been working hard on the delete form to customize injection issues:
- https://github.com/ploneintranet/ploneintranet/pull/674
- https://github.com/ploneintranet/ploneintranet/pull/675

The delete confirmation form, anyway does not fully comply to the prototype, even if the look is similar.
We miss for example the sentence "You are about to delete this ${context/portal_type}. Are you sure?".

But I would not be 100% loyal to prototype in this case.

**Comment by pilz** [comment]
@ale-rt  If the mentioned three PRs are merged (650, 674, 675), does that then make this PR obsolete?

**Comment by gyst** [comment]
@reinhardt on review this PR conflicts with the already merged work done by @ale-rt (#650, #674, #675).
Closing this PR but leaving the branch for now.

**Pull request closed without merging**
