### PR TITLE
Fix links to workspaces

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
@giacomos if you want you can merge it

**Comment by pbauer** [comment]
how about a test?

**Comment by ale-rt** [comment]
Yes @pbauer, I was talking about this with @giacomos.

There is also another issue I was talking about: when you submit a status update in the tile appears the user id instead of the fullname.

**Comment by pbauer** [comment]
The username is created in `ploneintranet.workspace.utils.get_workspace_activities` as `item.creator`

**Comment by pbauer** [comment]
I will merge this and work on a new pr for possible issues with the creator

**Pull request merged**
