### PR TITLE
Template Cases

### PR DESCRIPTION
**Pull request by cillianderoiste**
This adds a /template folder to the portal where template Case Workspaces can be added and configured. When you create a new Case object you choose which template Case to based it on. The template Case is then copied to /workspaces, along with its Placeful Workflow configuration and Todo items.

Note: There is no user interface to add an additional template Case item. You could copy an existing Case object and adjust the Placeful Workflow etc. via the ZMI or use ++add++ploneintranet.workspace.case and configure the workflow manually.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/184/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/314/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/321/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/323/
Test FAILed.

**Comment by cillianderoiste** [comment]
This is ready for review now.

**Pull request merged**
