### PR TITLE
Solr tweaks

### PR DESCRIPTION
**Pull request by mattss**
This PR includes a few solr-related improvements
- Cleans up the solr buildout inheritance setup to make it easier to re-use in deployments
- Enables connection pooling
- Ups the ngram size to 4 (an ngram size of 2 produces some pretty odd results such as a search for 'document' giving you results that contain the word 'do')
- Sets up a separate field for spellchecking. This improves the speed and accuracy of spelling suggestions, and stops you getting unhelpful stemmed spelling suggestions.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/215/
Test PASSed.

**Comment by mattss** [comment]
Update on this - I've moved the ngram size back down to '2', but moved it to an index-only filter. This supports livesearch style cases where 'do' should include results with 'document', but searching for 'document' should not include results that have the word 'do'.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/216/
Test PASSed.

**Pull request merged**
