### PR TITLE
Improvements to making a dev JS bundle for Diazo

### PR DESCRIPTION
**Pull request by jcbrand**
@gyst Can you please take a look?
1. The jsdev recipe must use the dev bundle, not the release bundle.
2. Avoid unnecessarily changing Diazo theme files when making dev bundle
   
   When making a development JS bundle, don't use "sed" to rename the JS bundle  being used in the Diazo theme files.
   
   Otherwise we have a bunch of dirty *.html files that should never be committed, causing a hazard.
   
   Instead, we simply copy over the ploneintranet-dev.js file to theme/static/generated/bundles/ploneintranet.js, which is the file being usedby the Diazo theme files and which is not under version control.

### CODE REVIEW

**Comment by do3cc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/4/
Test FAILed.

**Comment by jcbrand** [comment]
The test failure doesn't appear to have anything to do with this pull request.

**Comment by do3cc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/5/
Test FAILed.

**Comment by mattss** [comment]
Jenkins retest this please

**Comment by do3cc** [comment]
Can one of the admins verify this patch?

**Comment by jcbrand** [comment]
The problem was with the new JS bundle I released a while ago, there was a regression in the version of pat-raptor being used. I updated it, should hopefully work now.

**Comment by mattss** [comment]
Still appears to be an issue with the alert box popping up. Is that pat-raptor related?

**Comment by jcbrand** [comment]
@matss Yes, it's pat-raptor related. The tests on master passed with the newer JS bundle. I'm wondering whether the tests here were triggered before I merged master into this branch. Trying again manually now...

**Comment by gyst** [comment]
@jcbrand I've made a fix - enable the dev bundle to actually get loaded.

However Jenkins is still failing on Raptor regression.
http://jenkins.ploneintranet.net/job/complete.Ploneintranet.all.branches.even.broken.True/314/consoleFull#-987094442b55daa74-4590-49a8-959b-ec8d0928d875

**Comment by mattss** [comment]
I don't quite understand how the fetch-release stuff works. Master is now failing due to the raptor regression, which I'm sure it wasn't before. Is there an extra step we are missing in the test process?

**Comment by jcbrand** [comment]
@gyst, ok, but that means the minified bundle is no longer used, right? I'm personally fine with that, but didn't you want to use the minified file for demoing?

@matss Looks green to me on [Jenkins](http://jenkins.ploneintranet.net/) did it fail for you locally? We're still working out some kinks after moving out the prototype and rewriting some of the Makefile steps. This branch pins to a newer JS release which I'm 100% sure has the pat-raptor fix included. The master branch is still on an older release, so I can update it if necessary. However, Jenkins is green...

**Comment by mattss** [comment]
@jcbrand Odd. It looks like the build was failing due to pat-raptor after the last commits from @gyst (http://jenkins.ploneintranet.net/job/complete.Ploneintranet.master.False/157/console) but then @gyst manually triggered the build again and it passed: http://jenkins.ploneintranet.net/job/complete.Ploneintranet.master.False/158/

As there don't appear to be any code changes in this repo between those two test runs, is this related to the compiled prototype stuff that is being fetched?

**Comment by jcbrand** [comment]
> As there don't appear to be any code changes in this repo between those two test runs, is this related to the compiled prototype stuff that is being fetched?

One noteworthy difference between this branch and master is the version of ploneintranet.js which it fetches from products.syslab.com. The version in this branch fixes the pat-raptor regression.

This branch fetches a newer version than master. If master is failing due to the pat-raptor issue, then it's likely that the version it fetches still contains the regression. If it happens only intermittently, then perhaps there's a timing issue involved as well. In any case, the version in this branch is the most recent one.

**Comment by mattss** [comment]
Retest this please Jenkins

**Comment by do3cc** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/7/
Test PASSed.

**Comment by mattss** [comment]
Jenkins is now happy with this. @gyst any comments on @jcbrand's question from https://github.com/ploneintranet/ploneintranet/pull/195#issuecomment-101175569 regarding the minified version?

**Comment by pilz** [comment]
Master is currently breaking for me without this. The changes to the Makefile seem to me only necessary to the js team and not interfering with the python devs. So I see no reason to delay this. I vote to merge it.

**Comment by jcbrand** [comment]
I'm not aware of any blockers.

**Comment by pilz** [comment]
Ok, I'll push my luck.

**Pull request merged**
