### PR TITLE
Token will invalidate after use. Added test and adjusted messages.

### PR DESCRIPTION
**Pull request by allcaps**

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by mattss** [comment]
Ok to test

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by mattss** [comment]
Test this please jenkins.

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by mattss** [comment]
ok to test

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/65/
Test PASSed.

**Pull request merged**
