### PR TITLE
Skip unnecessary and expensive role lookups

### LINKED ISSUE #289: Performance Degradation for non-admins
As allan_neece entering a folder in a workspace takes a long time depending on the number of workspaces in the system.
It is quick for the admin user.

We tracked it down to the WorkspaceLocalRoleAdapter
https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/configure.zcml#L71-L73

Comment it out and folder loading for allan is quick again.

I don't immediately understand what the issue was that was solved here. @adamcheasley can you shed some light?
https://github.com/ploneintranet/ploneintranet/commit/b5edac6a42a05e0c096921135d08cc587d8903f1

### PR DESCRIPTION
**Pull request by mattss**
- Attempts to resolve https://github.com/ploneintranet/ploneintranet/issues/289

### CODE REVIEW

**Comment by mattss** [comment]
@pilz I think this may have been the issue. We were looking up all roles on the workspace even if the user wasn't the owner, but then only doing something useful later if they were the owner. I've added a clause to bail out early which seems to help.

**Comment by pilz** [comment]
Beautiful!

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/173/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/174/
Test PASSed.

**Comment by pilz** [comment]
Works for me

**Pull request merged**
