### PR TITLE
Editable user profiles

### PR DESCRIPTION
**Pull request by mattss**
Editable user profiles are here!

The goals and features of this PR are explained in the 'User profile' part of the docs, so I recommend running 'make docs' and view Development > Components > User Profiles before/whilst reviewing this.

The bottom line is that user profile fields are as customisable as possible, without integrators having to fork the theme or rewrite the profile template in any way.

Some highlights include:
- Custom z3c.form setup which provides prototype-compatible markup (on both 'view' and 'edit') that is dynamically built from the User Profile type and any enabled behaviours
- Registry settings for hiding fields from the user profile, or making them read-only on the profile (but still settable in code e.g. for external data sources)
- Registry setting for the 'location' vocabulary

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/327/
Test PASSed.

**Comment by mattss** [comment]
@pilz This now includes an 'address' field that was not in the original set of fields we outlined, but you mentioned for ikath and I thought it made sense as a default option.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/334/
Test PASSed.

**Comment by pilz** [comment]
Looks very well and works fine.
It just seems that only the mandatory fields respond to the read_only config, not the optional ones. 

screen shot 2015-07-03 at 15 41 53
screen shot 2015-07-03 at 15 41 38

**Comment by pilz** [comment]
I am tempted to merge anyway and make a ticket out of the read_only stuff… Anyone opposing?

**Comment by pilz** [comment]
Moved that into #368

**Comment by mattss** [comment]
retest this please

**Comment by mattss** [comment]
please test

**Comment by mattss** [comment]
Test this please I am losing my mind.

**Pull request merged**
