### PR TITLE
558 remove unwanted icons

### LINKED ISSUE #558: hide copy/share document actions
As allan_neece, go to
http://localhost:8080/Plone/workspaces/open-market-committee/manage-information/minutes-overview
- the copy icon should be hidden (not supported, wrong link)
- the share icon should be hidden (broken link, not supported yet, scheduled in #359)

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #558

### CODE REVIEW

**Comment by pysailor** [comment]
Manually re-running jenkins after it got stuck, for this PR it's
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/610/

**Comment by pysailor** [comment]
After a manual nudge, jenkins for this PR is now green:
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/610/

I assign this to @gyst for review, since it fixes an issue you reported #558

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pilz** [comment]
Works for me. I merge this since we will reactivate the share soon in another pr to allow downloading files, so I want to fix conflicts now.

**Pull request merged**
