### PR TITLE
New JS bundle

### PR DESCRIPTION
**Pull request by jcbrand**
Fixes the IE10 sidebar bug

See here: https://github.com/ploneintranet/ploneintranet.prototype/issues/156

The bug was in a regex in the parser. See here:
https://github.com/Patternslib/Patterns/commit/334b64957da88296b57be8d3b22726566abd8b00

### CODE REVIEW

**Comment by jcbrand** [comment]
Failing tests are again in events section. Looks like timing issues again.

**Comment by jcbrand** [comment]
DON'T MERGE. Looks like there might be a legitimate bug here.

**Comment by jcbrand** [comment]
Jenkins please test this

**Comment by gyst** [comment]
Failure in build 957 looks like a webdriver error.

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by pysailor** [comment]
Jenkins please test this

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
W00t, finally jenkins passed

**Pull request merged**
