### PR TITLE
update bundle and diazo to get relative dates and latest proto fixes in

### PR DESCRIPTION
**Pull request by pilz**

### CODE REVIEW

**Comment by pilz** [comment]
jenkins please retest this

**Comment by pilz** [comment]
jenkins please retest this

**Comment by pysailor** [comment]
Jenkins is re-testing: http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/608/

**Comment by pysailor** [comment]
jenkins test this please

**Comment by pysailor** [comment]
jenkins test this please

**Pull request merged**
