### PR TITLE
Configure i18n suppport for pat-date-picker

### PR DESCRIPTION
**Pull request by cillianderoiste**

### CODE REVIEW

**Comment by pysailor** [comment]
Jenkins test running http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/611/

**Comment by pysailor** [comment]
jenkins please test this

**Comment by pysailor** [comment]
jenkins please retest this

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
robot heisenbug? http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/623/robot/report/robot_log.html#s1-s5
Edit: Hmmm no, the date picker seems to cause this (panel footer disappears from visibility), I can reproduce locally!
What the heck? When then "end date" field loses focus, the panel footer disappears.

**Comment by pysailor** [comment]
I suspect this might be a bug in the validation: when the end date is entered and the field still has focus, a validation error is shown (required). 
In the footer, the "Create" button is disabled.
 screen shot 2015-08-08 at 07 09 14
Once the field loses focus, the panel footer disappears completely. Could be the attempt to re-enable the create button?

**Comment by pysailor** [comment]
After thorough debugging I can see that adding the `i18n` parameter to data-pat-date-picker causes the robot test failure. For some-reason, pat-validate will, after a date-string has been inserted into the input field and the fields loses focus, completely remove the panel footer with the buttons for create and cancel:

1) pat-date-picker field, after robot has written the date string
screen shot 2015-08-09 at 12 51 19

2) Lower part of the "Add event" panel after the field loses focus (the bottom edge is defined by where the browser window ends):
screen shot 2015-08-09 at 12 52 16

If I remove the `i18n` parameter that this PR introduces, the test passes. (And of course, if I remove the "required" attribute from the start and end inputs, it works too.) Although this error only seems to happen in a robot test, I cannot merge this PR because of it.

Additional consideration: Perhaps this is caused by faulty re-drawing of the panel after validation succeeds:

If I open the add event panel (lower half of my browser:),
screen shot 2015-08-09 at 12 52 35

then open the Inspector (notice how the buttons in the panel footer have moved up to stay visible:),
screen shot 2015-08-09 at 12 52 50

then then close the Inspector again, the panel gets redrawn, but the panel footer is now no longer visible:
screen shot 2015-08-09 at 12 53 03

Can @jcbrand or @adrianwhite or any other versed in javascript please look at this?

**Comment by ale-rt** [comment]
Already in quaive:
- quaive/ploneintranet@b87a2ee06233ffe0f9d78351e95c157a9126ab22
- quaive/ploneintranet@a7d0969b8787d8bc32da3f0e175cf1dcf3874ac1

**Pull request closed without merging**
