### PR TITLE
Implement the new extended sidebar

### PR DESCRIPTION
**Pull request by pilz**
Cornelis has done a sidebar extender button. This is specially interesting for the file sidebar where we now can show additional metadata like tags, modification date and author. It currently shows on the sidebars for docs, events and tasks plus on the members settings tab.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/256/
Test PASSed.

**Comment by gyst** [comment]
@pilz This merge conflicts with your other pulls I just merged. Can you plz fix?

**Comment by pilz** [comment]
merged!

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/258/
Test PASSed.

**Pull request merged**
