### PR TITLE
Fixes for template errors identified by running i18ndude

### PR DESCRIPTION
**Pull request by cillianderoiste**
This fixes errors identified by running ./synci18n.sh, but it may be that this also breaks things since I don't know what happens when there are duplicate tal:attributes for an element, and similar issues.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/236/
Test FAILed.

**Comment by pilz** [comment]
I reverted the search_template fix. Apparently the tal html parser is complaining about something that is working well in the browser. The error spit out by synci18n.sh/i18ndude is:

`````` python
There was an error processing ../search/browser/templates/search_template.pt
Traceback (most recent call last):
[..]
File "/opt/buildout.python/python-2.7/lib/python2.7/site-packages/zope/tal/talgenerator.py", line 563, in emitStartElement
"define-macro may not be used with use-macro", position)
METALError: define-macro may not be used with use-macro, at line 1, column 1, in file ../search/browser/templates/search_template.pt```

Removing either of these cripples the search. Not sure yet how to reformat that. 
``````

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/237/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/238/
Test PASSed.

**Pull request merged**
