### PR TITLE
Personalized datastructures

### PR DESCRIPTION
**Pull request by gyst**
This generalizes "follow" and "like" into a framework to express arbitrary relations between users and objects (be they content, status updates or other users).

The implementation consistently uses separate code paths for content, users and statusupdates to make it easy to resolve any returned object ids (content uuids, user userids, status.id) into the referenced object - that resolving needs to be different for each of these types.

"Follow" has been generalized to also support following content or tags, in addition to users.

Newly implemented is tagging, by users, of content and other users. This can be used as a backend for profile endorsements, which is the tagging of users by other users.

@pbauer this drastically refactors the like code you've worked on without changing the functionality. You may be interested to have a look.

@mattss this provides a fully realized backend for the user follow and endorsement stories your team is planning to work on shortly :-)

All tests green on this branch locally, before merge.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/18/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/19/
Test FAILed.

**Comment by mattss** [comment]
@gyst master has been updated with some fixes for the robot tests. Please could you rebase this pr?

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/26/
Test PASSed.

**Comment by mattss** [comment]
I agree with comments @jaroel regarding publishTraverse stuff. This and the context-based toggling browser views will give us issues with Plone's CSRF protection.

**Pull request merged**
