### PR TITLE
Userpicker members

### PR DESCRIPTION
**Pull request by cillianderoiste**
Adds the basic functionality to be able to add a member to a workspace.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/104/
Test FAILed.

**Comment by gyst** [comment]
@cillianderoiste Sorry I had to mess with your work to undo an inadvertent push by Matt. I cherry-picked e74f84b on master but removed the merge commit a8b8331. I suggest you do 'git checkout master; git fetch; git reset --hard origin/master; git checkout userpicker-members; git rebase -i master' and then drop the merge commit. After that you can do a 'git push --force' to update the pull request branch.

**Comment by gyst** [comment]
Alternatively you can create a new branch and cherry-pick the actual changes.

**Comment by cillianderoiste** [comment]
@gyst no problemo, and thanks for the heads-up! I'll fix the tests and push a new branch when it's ready.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/115/
Test PASSed.

**Comment by gyst** [comment]
Cool! This already closes a story I just scheduled for next week's sprint! (Assembla 257)

**Pull request merged**
