### PR TITLE
Basic notifications for status updates

### PR DESCRIPTION
**Pull request by mattss**
See https://github.com/ploneintranet/ploneintranet/issues/371 for spec.

I've tried to re-use as much of the existing ploneintranet.notifications framework as possible in the interests of time, but I am not convinced the current architecture is quite right for the future.

Still to do - some way to link directly to status updates from the
notifications page

### CODE REVIEW

**Comment by gyst** [comment]
Opening the notifications box marks notifications as read, which is cool. What is awkward though, is that the unread counter doesn't change. So you keep having this red notifier of "unread" messages and when you click it, it says "no unread notifications".

Even in the absence of websockets push, this can be fixed by, on opening the notifications box, not only injecting the notifications list but also resetting the unread marker as a secondary injection.

**Comment by gyst** [comment]
Helper view follow-up issue #486

**Comment by mattss** [comment]
@gyst At the moment the notifications popup is using an ajax pat-tooltip, rather than pat-inject directly, so I'm not quite sure how or if you can add secondary injection options. I could experiment with changing it to a pat-inject, but I'm a bit concerned about straying too far from the prototype.

**Comment by gyst** [comment]
@mattss Various issues:
- I've tried to fix some URLs in the notification but am stumped by the actual message url. Leaving that empty results in the message pointing to the current page (an A tag without HREF) which is invalid if you're accessing the notification box from a page other than the dashboard. You can see that in action if you go to /notifications?showall=1.
-  There's another bug there in showall: the menu is not diazo injected like it should and displays the proto menu item. E.g. dashboard URL should be "/" not "/dashboard.html".
- Finally: security. If you activate a view that has a security comment you should check against anon access. In this case that results in a traceback. I'd rather have that handled explicitly with a check against anonymous and a redirect to "/" if so.

**Comment by mattss** [comment]
@gyst I think i've resolved the issues you were having:
- URLs - updated the template to use the url that you added (to the root of the site)
- Menu - the notifications template was quite old, so I've updated the relevant classes and tweaked the diazo rules to fix this
- Permissions - tied them to ploneintranet.viewsite as per other site-level views

**Comment by gyst** [comment]
Looking good, thanks!

**Pull request merged**
