### PR TITLE
Moar hiding

### PR DESCRIPTION
**Pull request by gyst**
Hide news and task tiles on dashboard

Jenkins is green.
http://jenkins.ploneintranet.net/view/All/job/complete.Ploneintranet.all.branches.even.broken.True/301/

### CODE REVIEW

**Comment by do3cc** [comment]
Can one of the admins verify this patch?

**Comment by mattss** [comment]
Ignore the above comment - jenkins pull request integration in progress :)

**Comment by mattss** [comment]
Ok to test

**Comment by do3cc** [comment]
?? I don't remember playing with this for this repo

**Comment by mattss** [comment]
Sorry @do3cc looks like Jenkins was set up to use your credentials for the pull request plugin.

**Comment by do3cc** [comment]
I don't mind the noise. It seems jenkins did not test yet

**Comment by do3cc** [comment]
Ok to test

**Comment by do3cc** [comment]
Can one of the admins verify this patch?

**Pull request merged**
