### PR TITLE
Profile images

### PR DESCRIPTION
**Pull request by mattss**
Prior to this, profile images were still provided by the old plone 'portrait' storage. This moves them to the actual user profile DX content, and provides a new ploneintranet.api method for accessing them.

This also means we take advantage of plone.app.imaging to properly crop avatar images, hopefully resolving #84

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/212/
Test FAILed.

**Comment by mattss** [comment]
Woweee something doesn't like this. I think this may be a setup issue in the suite. Will investigate!

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/213/
Test PASSed.

**Comment by mattss** [comment]
@cillianderoiste do you have a moment to check this today?

**Pull request merged**
