### PR TITLE
Tag auto suggest 2

### PR DESCRIPTION
**Pull request by cillianderoiste**
Follow up from #343 based on master instead of the obsolete branch personalized-tagging.

This fixes suggestions for tags.

### CODE REVIEW

**Comment by cillianderoiste** [comment]
retest this please jenkins

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by gyst** [comment]
Jenkins retest this please

**Comment by cillianderoiste** [comment]
I missed some broken unit test, I'll fix them.

**Comment by cillianderoiste** [comment]
This is ready for review.

**Pull request merged**
