### PR TITLE
Event: Fix add view, and refactor the event_fields macro

### PR DESCRIPTION
**Pull request by cillianderoiste**
It wasn't possible to add a new event because of the duplicate
Description fields, and the add_event view Description was acquiring the
Description of the container.

### CODE REVIEW

**Comment by cillianderoiste** [comment]
Actually, I see that adding events still doesn't work. I'm looking into it.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/229/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/230/
Test PASSed.

**Comment by mattss** [comment]
Can we get a robot test for adding events?

**Comment by cillianderoiste** [comment]
I agree, robot tests are badly needed for Events.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/248/
Test PASSed.

**Comment by gyst** [comment]
Please do not merge this pull.
- It updates the generated theme, which should _always_ be done in a separate PR. Now it will conflict with 861ce02a5c7ce4e72cfeab6338f46d7b68620c78 which is already merged.
- It conflicts with my massive refactor in pull #328 . Let's work together on porting the changes in this PR to the new approach introduced there.

I'm closing this PR, please keep the branch so we can use that as a base for a new PR once #328 is merged.

**Comment by gyst** [comment]
Uhm, reopening or else we'll forget it needs to be done...

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/264/
Test PASSed.

**Comment by cillianderoiste** [comment]
Superseded by #332

**Pull request closed without merging**
