### PR TITLE
Decrease code complexity in get_groups_children

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by gyst** [comment]
Jenkins test this please test

**Comment by gyst** [comment]
The downside from complexity refactoring is that the diffs are complex. I'm not the original author of this code and in no position to review.

**Comment by ale-rt** [comment]
I would really like to have this merged this before working on #591

**Comment by gyst** [comment]
I think @pilz is the only one capable of reviewing this PR, sorry.

**Comment by pilz** [comment]
please test please

**Comment by pilz** [comment]
Stuck in test fixing. All is reasonable, I just need to get tests to pass first…

**Pull request closed without merging**
