### PR TITLE
Selenium upgrades

### PR DESCRIPTION
**Pull request by mattss**
Update selenium libraries in the hope of fixing jenkins

### CODE REVIEW

**Comment by pilz** [comment]
+1

**Comment by mattss** [comment]
Jenkins please test this please now please dear goodness. Please.

**Comment by mattss** [comment]
Jenkins please retest this.

**Comment by mattss** [comment]
Jenkins test this please.

**Comment by mattss** [comment]
Jenkins seems to be working again. Closing for now.

**Pull request closed without merging**
