### PR TITLE
buildout.d (#49)

### PR DESCRIPTION
**Pull request by gyst**
Refactor and simplify buildout structure. Needed to support simple eggified Venus build.

### CODE REVIEW

**Comment by gyst** [comment]
Test failure in build 962 looks like a Jenkins issue. Please test this.

**Comment by gyst** [comment]
@cillian do you want to review and merge this or shall I self-merge?

**Comment by cillian** [comment]
@gyst I think you meant @cillianderoiste

**Comment by gyst** [comment]
Yes I did but Waffle does not give me autocomplete :-). Sorry!

**Comment by cillian** [comment]
Ah ok, no prob!

**Pull request merged**
