### PR TITLE
317: add a custom widget to save comma separated strings as a tuple

### PR DESCRIPTION
**Pull request by cillianderoiste**
This allows tags to be saved: #317

I couldn't find a place where tags are exposed in the UI for this branch, so there aren't any new robot tests for it. The existing tagging tests should continue to work.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/285/
Test PASSed.

**Comment by mattss** [comment]
Agree that robot test not really possible here - but could you do an integration test? Would be good to verify that this is now working, to prevent it reoccuring.

**Comment by gyst** [comment]
On manual testing this doesn't fix the problem.
To reproduce:
- go to http://localhost:8080/Plone/workspaces/service-announcements/terms-and-conditions/
- set some tags
- inspect the object in the backend::
  
  > > > doc = portal.workspaces['service-announcements']['terms-and-conditions']
  > > > doc.subject
  > > > (u'oldtag1,oldtag2,newtag1,newtag2',)

This ought to be instead:

```
(u'oldtag1', u'oldtag2', u'newtag1', u'newtag2',)
```

**Comment by cillianderoiste** [comment]
I've merged from master and added a simple test to verify that tags are saved as a tuple of strings. I've also tested manually that tags added to workspaces/service-announcements/terms-and-conditions are saved as a tuple and it should work fine now.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/296/
Test PASSed.

**Comment by pilz** [comment]
@gyst @mattss any takers?

**Pull request merged**
