### PR TITLE
Apps view

### PR DESCRIPTION
**Pull request by ckirchhoff**
Add a view for apps. Make the link of the case manager point to "case-manager/" and all others to "#"

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by gyst** [comment]
@ckirchhoff  All disabled apps should have the class "disabled".

**Comment by gyst** [comment]
Inactive apps should trigger "App not available" modal.
Jenkins test this please.

**Comment by pilz** [comment]
Jenkins please test this

**Comment by pilz** [comment]
please test this please retest this

**Comment by gyst** [comment]
The linked /@@case-manager view gives a 404.

**Comment by pilz** [comment]
Yes, because this requires our case-manager branch to be merged. So we better deactivate that for now as well I guess?

**Comment by gyst** [comment]
Yes please deactivate for now.

**Comment by pilz** [comment]
disabled now.

**Comment by gyst** [comment]
Jenkins stop sulking. Test this please test this.

**Pull request merged**
