### PR TITLE
Workspace security 2

### PR DESCRIPTION
**Pull request by wengole**
This PR supersedes the previous workspace security PR.

It maintains the sidebar functionality, but disables any elements if the user does not have "Manage Workspace" permission

### CODE REVIEW

**Comment by wengole** [comment]
@gyst in relation to https://github.com/ploneintranet/ploneintranet/pull/111#issuecomment-86971065, this @mattss idea to make the code more DRY.

I will re-refactor it into view code...

**Comment by mattss** [comment]
Yeah sorry - this code was being repeated everywhere, but in retrospect the model was not the place to consolidate it to.

**Comment by wengole** [comment]
@gyst re-refactoring done

**Comment by gyst** [comment]
@wengole If you could update this branch and fix the test failures?

**Comment by wengole** [comment]
@gyst all fixed ready for merge

**Comment by wengole** [comment]
@gyst Please merge before Jenkins changes its mind :+1:

**Comment by mattss** [comment]
Recent Jenkins error seems to be a 503 download error, so I'm ignoring it.

**Pull request merged**
