### PR TITLE
Add coveralls.io support to jenkins

### PR DESCRIPTION
**Pull request by mattss**

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/48/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/49/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/50/
Test PASSed.

**Comment by mattss** [comment]
Coveralls integration not quite working. Please don't merge yet(!)

**Comment by mattss** [comment]
This is not going to work as intended. Closing for now.

**Pull request closed without merging**
