### PR TITLE
Dynamic search UI

### PR DESCRIPTION
**Pull request by mattss**
This updates the search UI so that the search options in the LH column can be customised using the existing registry settings.

See doc updates for details - bottom line is that any field registered as _both_ a filter and a facet field will appear in the LH column and allow users to limit their results using that field.

Also in this PR - date range now uses 'modified' as per prototype (rather than 'created') as previously)

### CODE REVIEW

**Comment by mattss** [comment]
@pilz @cillianderoiste This is what you will need to get custom fields such as 'document_type' into the main search UI.

**Comment by mattss** [comment]
Test please jenkins

**Comment by mattss** [comment]
Test this please

**Comment by mattss** [comment]
Test this please jenkins

**Comment by mattss** [comment]
test this please

**Comment by mattss** [comment]
retest this please

**Comment by mattss** [comment]
retest this please jenkins

**Comment by mattss** [comment]
Ready for merge. This is needed for adding custom filters to the search UI.

**Comment by mattss** [comment]
(Ready for review, rather!)

**Comment by gyst** [comment]
I've seen you demo this :-) so OK to merge.

**Pull request merged**
