### PR TITLE
Fix delete_confirmation

### LINKED ISSUE #527: Cancelling a delete confirmation in workspace destroys its view
When I go into the Open Market Committee workspace as allan_neece,
navigate to manage information / Budget ProposaI,
press the delete button
and cancel the delete confirmation request modal:

I only see the budget proposlal image centered on screen and all surrounding navigation/workspace information is gone. 

delete-confirmation-cancel

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #527

### CODE REVIEW

**Comment by gyst** [comment]
Does this PR duplicate #499?

**Comment by ale-rt** [comment]
No, but nice to know.
Will do it all together.

**Comment by reinhardt** [comment]
In what way does this fix the delete_confirmation? Also, do we really need the redirect on cancel? Can't we just do a close-panel in pat-modal?

**Comment by reinhardt** [comment]
> In what way does this fix the delete_confirmation?

Sorry, forget that part, I missed the ticket reference.

**Comment by ale-rt** [comment]
I think the problem is related to injection: after clicking cancel the default delete_confirmation form of plone returns the image.
This was an upstream bug that involves also pat-plone-modal and that was fixed yesterday.
- https://github.com/plone/plone.app.content/pull/41

Even with this fix the Plone vanilla behaviour still does not play well with our injection.
Now that I know about #499 everything gets more clear: the whole form was already scheduled for a lifting :)

Anyway my contribution is not ready at all (I have failing tests).

**Comment by reinhardt** [comment]
> I think the problem is related to injection: after clicking cancel the default delete_confirmation form of plone returns the image.

Thus my question: do we really need the redirect (injection) on cancel? Can't we just do a close-panel in pat-modal? s.a. #499

**Comment by ale-rt** [comment]
> Thus my question: do we really need the redirect (injection) on cancel? Can't we just do a close-panel in pat-modal? s.a. #499

Yeah, that is great and preferred!

In any case we do want to patch delete_confirmation redirect. 
The actual status of the form is broken: it has to redirect to the view url and not the absolute_url when we click cancel.

**Comment by ale-rt** [comment]
@reinhardt, being that you have knowledge on this, would you review/merge this?

I am sorry this conflicts with the ongoing work on #499, but as I can see that branch has already merge conflicts.

The main difference with the branch you, @cillianderoiste and @pilz were working is that the view is in pi.theme and that it uses the vanilla Plone template.

I am sorry but I was not aware of your branch :(

**Comment by gyst** [comment]
@ale-rt There should not be any browser views in ploneintranet.theme. Can you move this to ploneintranet.layout please? That's where all our global views reside. The theme should be css/js/diazo only.

**Comment by ale-rt** [comment]
Sure, moving this

**Comment by reinhardt** [comment]
Yup, I'll review.

**Comment by ale-rt** [comment]
As it was asked I moved the view to pi.layout, the PR is ready for review :)

**Comment by reinhardt** [comment]
Ah, someone was quicker than me.

**Pull request merged**
