### PR TITLE
Decrease code complexity

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by gyst** [comment]
Jenkins please test this please

**Comment by gyst** [comment]
Jenkins don't be a problem. test this please test

**Comment by gyst** [comment]
Diff looks like a clean improvement to me. Merge hangs on Jenkins issue #731

**Comment by gyst** [comment]
Code diff looks clean, merge hangs on getting a green PR build see #731

**Comment by ale-rt** [comment]
test this please

**Comment by gyst** [comment]
Jenkins test this please.

**Pull request merged**
