### PR TITLE
Better add workspace permission

### PR DESCRIPTION
**Pull request by pysailor**
Also, don't show "Add workspace" link if the user does not have the required permission

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/55/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/57/
Test FAILed.

**Comment by pysailor** [comment]
jenkins test this

**Comment by pysailor** [comment]
jenkins retest this

**Comment by pysailor** [comment]
Retest this please jenkins

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/58/
Test PASSed.

**Comment by pysailor** [comment]
Retest this please jenkins

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/59/
Test PASSed.

**Comment by mattss** [comment]
Looks good.

**Pull request merged**
