### PR TITLE
Remove default content from Plone

### PR DESCRIPTION
**Pull request by fredvd**
when we set up plone intranet

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Jenkins please test this please

**Comment by fredvd** [comment]
Fixes #440

**Comment by jcbrand** [comment]
FYI: cleanup is a noun, the verb is written separately, clean up.

**Comment by fredvd** [comment]
@jcbrand. Thanks . Will clean up cleanup. :-)

**Comment by jcbrand** [comment]
@fredvd The grammar is a bit tricky in the context of programming/CS, because of the way in which for example **setup** is commonly used as a verb (although strictly speaking it's incorrect grammar).

I recently wrote a blog post on it and many people disagreed with me (some with good reasons why). 

Personally, I think it's ok if methods **don't** separate the words (e.g. setup_tests <=> set_up_tests) because it sometimes looks clunky, but IMHO the explanatory comments and docs should at least have proper grammar and ideally the programmer should know what the correct grammar is.

Anyway... probably just bikeshedding here! My 2c.

**Pull request merged**
