### PR TITLE
Fix naming issues with social packages

### PR DESCRIPTION
**Pull request by mattss**
- PloneIntranet -> Plone Intranet for consistency with existing
  packages
- Add 'Social' to some of the social eggs to remove confusion with
  existing eggs (e.g. theme)

### CODE REVIEW

**Comment by mattss** [comment]
@gyst @pysailor Quite a few changes here but all text/translation related. Hopefully this will make things clearer!

**Comment by pysailor** [comment]
Looks good to me. But @gyst you're the "owner" so I think you should have the final say & merge.

**Comment by mattss** [comment]
@gyst do you want to retain final say on plone social changes like this? Or should we just get on with this kind of thing now that we've merged the codebases?

**Comment by gyst** [comment]
@mattss This is really just infrastructure maintenance for which I don't need veto rights :-). Also I'm getting so much mail I might not notice a mention.

**Pull request merged**
