### PR TITLE
Solr search implementation

### PR DESCRIPTION
**Pull request by mattss**
Here it is! Solr search at last. To activate solr you need to manually build out with 'solr.cfg'. 

There's a lot going on here and much of the complexity is in the test setup (surprise surprise). 
The default test setup, just run the zcatalog-backed tests, and will ignore all the solr tests. You can run the solr tests by building out with solr.cfg and running ./bin/test as normal (or ./bin/test -s ploneintranet.search.solr).

It is worth running 'make docs' and then reading through the 'Developer documentation > Components > Search' page before looking at any of this code, as it will help you understand the bigger picture.

### CODE REVIEW

**Comment by mattss** [comment]
@pbauer @pysailor anyone feeling brave?

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/186/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/187/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/188/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/190/
Test PASSed.

**Comment by mattss** [comment]
OK solr test passing now sorry for the initial failures!

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/206/
Test PASSed.

**Comment by mattss** [comment]
This pull request is very noisy already. I'm going to merge master and then re-open it.

**Pull request closed without merging**
