### PR TITLE
Update Selenium to 2.46.0

### LINKED ISSUE #534: robotframework tests cause "firefox unexpectedly quits" errors
When running the ploneintranet.suite robotframework tests crash firefox startups, but the tests still run. 
Upgrading to selenium 2.46.0 from 2.45.0 fixes this.

### PR DESCRIPTION
**Pull request by fredvd**
Closes #534.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by mattss** [comment]
Test this please

**Comment by gyst** [comment]
Closing this ticket, keeping the branch.

**Pull request closed without merging**
