### PR TITLE
sidebar open by default when viewing a document directly

### LINKED ISSUE #77: The sidebar should be open by default when viewing a document directly
This requires applying the sidebar-left-open class to the body.

### PR DESCRIPTION
**Pull request by pbauer**
fix #77

### CODE REVIEW

**Comment by mattss** [comment]
The diazo rules are pretty horrific, and adding to them makes me sad.

**Comment by pbauer** [comment]
@mattss @pilz any alternative solutions?

**Comment by mattss** [comment]
Unless @pilz has any, I think that re-thinking the diazo rules is probably a separate, larger task unfortunately.

**Comment by pbauer** [comment]
then we should merge this until we have a better solution

**Comment by mattss** [comment]
Agreed :(

**Comment by pilz** [comment]
Yes, but we will look at the diazo rules soon :) All will be good!

**Pull request merged**
