### PR TITLE
Plonesocial security 2

### PR DESCRIPTION
**Pull request by gyst**
This is a full security audit of the microblog stack.
- protect write access with AddStatusUpdate
- protect all read accessors with ViewStatusUpdate
- is aware of local security context in workspaces (via api.user.has_permission)
- caches expensive security check in ramcache

Also reorganizes implementation and tests for readability, which creates noise in the diff but clarity in the actual code.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/75/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/76/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/77/
Test PASSed.

**Comment by gyst** [comment]
@mattss you raised the issue, hopefully you'll want to merge the pull?
Test coverage on the workspace security manager added in suite/tests/test_microblog_security.

**Comment by gyst** [comment]
@jaroel Maybe I can get you to review and merge this?

**Pull request merged**
