### PR TITLE
Basic search implementation

### PR DESCRIPTION
**Pull request by mattss**
This is an initial implementation of the search, including:
- Generic search API designed to allow multiple backend search implementations
- Initially backed by the portal_catalog
- Basic implementation of the 'all' search results tab (others to follow)
- Filtering by 'friendly type' (groups file content by their mime type descriptions)
- Filtering by tag
- Filtering by date range
- Robot-based acceptance tests

This has been code-reviewed within Netsight, but please comment if you notice anything funny.

Work is ongoing to replace the backend with solr - which will form a future pull request.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/105/
Test FAILed.

**Comment by mattss** [comment]
Irritating timing issues with robot tests. Will try and resolve.

**Comment by mattss** [comment]
Closing this pull request as it was opened from an unhelpful branch. Will open another shortly.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/109/
Test PASSed.

**Pull request closed without merging**
