### PR TITLE
Validate content add forms

### PR DESCRIPTION
**Pull request by ckirchhoff**
simple change to enable validation on content add forms. This prevents users from adding content without a title. As a small add-on events now also have preset dates.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Add to whitelist

**Comment by gyst** [comment]
Jenkins please test this

**Comment by gyst** [comment]
@ckirchhoff can you please rebase this so we can test a clean merge?

**Comment by gyst** [comment]
Jenkins test this please

**Comment by pilz** [comment]
merged master

**Comment by pilz** [comment]
Jenkins test this please retest this

**Comment by pilz** [comment]
This needs js support. pat-validate doesn't revalidate on typing, you need to defocus the title field. This is a usability issue. I'll check with @jcbrand

**Comment by pilz** [comment]
Depends on #535

**Comment by pilz** [comment]
Will fix #434

**Comment by pilz** [comment]
This validates the title and start/end fields properly. However validation whether an end date is before a start date is irritatingly difficult with parsley at the moment. We have looked at using validate.js, which is applying validation in a declarative way and that would be much better and more flexible. But at this point this would cost probably a few days to properly implement and test and switch, so I'd say we skip that for later.

**Comment by pilz** [comment]
With this pull request, it is now possible to properly apply pat-validate on forms and a required="required" on required fields.

**Comment by pilz** [comment]
Jenkins test this please retest this

**Comment by gyst** [comment]
Jenkins please test this again.

**Comment by gyst** [comment]
#535 was merged before the test failed.

**Comment by gyst** [comment]
Jenkins test this please

**Comment by pilz** [comment]
What a pace. Another try. Jenkins test this please

**Comment by pilz** [comment]
:)

**Pull request merged**
