### PR TITLE
538 check i18n

### PR DESCRIPTION
**Pull request by allcaps**
Diverse i18n fixes. #538

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by mauritsvanrees** [comment]
Looks good to me. Jenkins, please test this.  Not sure if I am admin there.

**Comment by gyst** [comment]
Jenkins please test this please

**Comment by pilz** [comment]
Jenkins please test this please

**Comment by allcaps** [comment]
@gyst @pilz I love to see this get merged before the party :)

**Comment by pilz** [comment]
Jenkins please test this please

**Comment by pilz** [comment]
I think we fixed it. Let's see what jenkins says :)

**Comment by allcaps** [comment]
I believe the previous build was already successful.

**Comment by pilz** [comment]
Nae, not yet. we have 3 reds so far.

**Comment by pilz** [comment]
green! yay!

**Pull request merged**
