### PR TITLE
Dexterity update handle no value

### PR DESCRIPTION
**Pull request by cillianderoiste**
This is a follow up from #390 which was merged and then reverted. It needs further work and testing before it can be merged. The problem it addresses is that submitting the correct empty value for a field (NO_VALUE) is currently ignored. This means that some fields can't be reset. We have this problem with a field we added to iKath (registration_number).

The current problem with this PR is that a POST request to the (edit) view of an item will cause any fields not included in the request to be set to the default. Perhaps it is enough to only update the fields which are in the request.form (in dexterity_update).

### CODE REVIEW

**Comment by gyst** [comment]
Jenkins retest this please

**Comment by gyst** [comment]
Please provide integration test coverage, this is key functionality that is exercised a lot.

**Comment by reinhardt** [comment]
If it was only a matter of updating the tests or adding new cases I would agree that this has to be done first. However it looks like there never have been any tests for dexterity_update, so I would argue that it is a separate task to write the missing tests. I would merge this now and then add a ticket for writing tests for dexterity_update. @gyst, does this make sense?

**Comment by gyst** [comment]
Yes Manuel ok.

On August 10, 2015 2:34:28 PM GMT+02:00, Manuel Reinhardt notifications@github.com wrote:

> If it was only a matter of updating the tests or adding new cases I
> would agree that this has to be done first. However it looks like there
> never have been any tests for dexterity_update, so I would argue that
> it is a separate task to write the missing tests. I would merge this
> now and then add a ticket for writing tests for dexterity_update.
> @gyst, does this make sense?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ploneintranet/ploneintranet/pull/471#issuecomment-129427750

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gyst** [comment]
Can we please get a bug reproduction scenario for this in vanilla plone intranet? As it is, it's impossible for me to either merge or work on this. @reinhardt what is your manual test scenario?

**Comment by reinhardt** [comment]
I hope @cillianderoiste can expand on this, but the test case is basically setting a value for a field, then removing the value. The new empty value is not stored but the old value retained. AFAIK only certain field types are affected.

**Comment by gyst** [comment]
On 28/08/15 09:44, Manuel Reinhardt wrote:

> I hope @cillianderoiste https://github.com/cillianderoiste can expand
> on this, but the test case is basically setting a value for a field,
> then removing the value. The new empty value is not stored but the old
> value retained. AFAIK only certain field types are affected.

OK. And what is the reason @pilz reverted the earlier PR containing the
same changeset as this one? We need a scenario for that reason as well.

## :*CU#

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by cillianderoiste** [comment]
In iKath we have fields which use vocabularies which cannot be unset. I can cook up a test for this.

In the version that @pilz reverted, posting an empty request would reset all fields. In the current version only fields which are in the request are modified.

**Comment by cillianderoiste** [comment]
Sorry for the noise. I think there is no need for this. We were using a select with a Choice field which was missing value="--NOVALUE--" for resetting the field, and we were also using a Choice field for a text input with pat-autosuggest. I'll close this PR.

**Pull request closed without merging**
