### PR TITLE
improve browser layer manipulation documentation

### PR DESCRIPTION
**Pull request by gyst**
Extract 'app protocol' documentation into separate page, and expand.
Move themswitcher documentation to frontend section.

### CODE REVIEW

**Comment by gyst** [comment]
@pbauer since we discussed this you may be interested in reviewing and merging this.

**Comment by pysailor** [comment]
jenkins test this please

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by gyst** [comment]
Documentation and docstring change only, merging it myself.

**Pull request merged**
