### PR TITLE
Complete i18n

### PR DESCRIPTION
**Pull request by ckirchhoff**
Mostly missing i18n tags. Also some translation from German to English and I added placeholder attributes to pat-autosuggest fields, because pat-autosuggest's own placeholders are not translatable.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Jenkins test this please

**Comment by gyst** [comment]
Jenkins test this please

**Comment by gyst** [comment]
Jenkins test this please

**Pull request merged**
