### PR TITLE
Unicode fixes

### PR DESCRIPTION
**Pull request by pysailor**

### CODE REVIEW

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by gyst** [comment]
Jenkins please test this

**Comment by pysailor** [comment]
Don't merge this, since @gyst is working on similar stuff in ploneintranet/ploneintranet/tree/library_utf8_tags

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pilz** [comment]
test please

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by gyst** [comment]
Superseded by #725

**Pull request closed without merging**
