### PR TITLE
Bulk actions for copy/paste/cut/delete

### PR DESCRIPTION
**Pull request by pilz**

### CODE REVIEW

**Comment by pilz** [comment]
jenkins please retest this

**Comment by pilz** [comment]
test please

**Comment by pysailor** [comment]
@pilz I assume we don't actually want the .pyo files you commited? Can I remove them again?
I'm looking at the robot tests now, I get the same failures locally.

**Comment by pilz** [comment]
Yup,copy paste mistake.

I saw the errors locally this morning, fixed the unittest already, then interrupted.

Alexander Pilz (mobil)

**Comment by pysailor** [comment]
More robot failures which did not appear before. What's going on??

**Comment by pysailor** [comment]
Gah, the worst kind of heisenbug!

```
UnexpectedAlertPresentException: Alert Text: This page is asking you to confirm that you want to leave - data you have entered may not be saved.
```

<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>

**Pull request merged**
