### PR TITLE
Enable download

### PR DESCRIPTION
**Pull request by pilz**
Currently, files can't be downloaded anymore. This reenables the sharing icon on the document view with the only action to download the item.

### CODE REVIEW

**Comment by pilz** [comment]
Module ploneintranet.workspace.browser.add_content, line 146, in default_end
  Module DateTime.DateTime, line 440, in **init**
  Module DateTime.DateTime, line 757, in _parse_args
TimeError: Invalid time: 2015/08/12 24:45

How is that possible? I try again hoping for a one timer

**Comment by pilz** [comment]
jenkins please retest this

**Comment by ale-rt** [comment]
Reegarding your issue the problem is here:
- https://github.com/ploneintranet/ploneintranet/blob/master/src/ploneintranet/workspace/browser/add_content.py#L145

It should be:

``` python
str((int(parts[0]) + 1)%24)
```

or even better work with DateTime() + 1./24.

I am using a similar approach in #600

**Comment by ale-rt** [comment]
Added #673 to quick fix this

**Pull request merged**
