### PR TITLE
Themeswitching

### PR DESCRIPTION
**Pull request by gyst**
This PR introduces a fallback to Barceloneta in the Plone Intranet stack.

NB this involves not only the diff of this pull, but please also review the upstream changes for which I will issue separate upstream pull requests when this ploneintranet PR is merged:
- Products.CMFPlone change in theme cache handling
  https://github.com/ploneintranet/Products.CMFPlone/commit/815044838d7a8732ff69d740067d3ab2e8f39ae0
- plone.app.theming introduction of policy adapter
  https://github.com/ploneintranet/plone.app.theming/commit/48f94bbb6a08e1f42ce2c8c2f433b8b7561918c4

Rationale and documentation see docs.
https://github.com/ploneintranet/ploneintranet/blob/themeswitching/docs/development/components/themeswitcher.rst

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/149/
Test PASSed.

**Comment by gyst** [comment]
@pilz This one is for you :-)

**Comment by pilz** [comment]
Wow, I had a first read of the docs and the code and it looks clear and straightforward. Tomorrow I will give it a spin.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/153/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/203/
Test PASSed.

**Comment by pilz** [comment]
Themeswitching works as advertised and I don't even find any suspicious js errors in the console when doing it. 

So far I noticed:
- Dashboard doesn't render in Barceloneta, we need to provide a proper alternative
- There are social links floating around the logo (Notifications(0) and Messages)
- Workspaces doesn't render in Barceloneta, we need to provide an alternative.
- How do we treat editing PI content types like workspaces or todos in Barceloneta?
- There should probably be a little switch button ("View page in PI Theme / View page in CMS") providing a preview function when working in the CMS.
- Search is broken in Barceloneta

All of these are expected side effects which need attention, but that is a followup task of this.
Of course we need to do more polishing, like assure that all our PI customisations only apply to the PI theme layer. I am happy to merge this now so that everybody can experiment with it and find/solve rough edges of having two themes coexist.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/204/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/205/
Test PASSed.

**Pull request merged**
