### PR TITLE
upgrade to Plone 5.0b2

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by pbauer** [comment]
Why is that not tested on jenkins?

**Comment by mattss** [comment]
Ok to test

**Comment by pbauer** [comment]
Merge only after the release of mercury

**Comment by gyst** [comment]
Jenkins please test this.

**Comment by gyst** [comment]
add to whitelist

**Comment by gyst** [comment]
ok to test

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/91/
Test FAILed.

**Comment by gyst** [comment]
Test failure is a jenkins build failure. test please

**Comment by gyst** [comment]
please test

**Comment by gyst** [comment]
@mattss The breakage is Jenkins-specific (and lowlevel: AccessControl module).
Locally this branch is fully green for me. 
Total: 518 tests, 0 failures, 0 errors, 5 skipped in 14 minutes 57.696 seconds.

**Comment by mattss** [comment]
@gyst can you confirm what version of AccessControl you have in your passing build?

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/92/
Test FAILed.

**Comment by mattss** [comment]
Retest this please Jenkins

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/93/
Test FAILed.

**Comment by mattss** [comment]
Jenkins you and I are going to have a falling out soon.

**Comment by gyst** [comment]
@mattss Not Jenkin's fault this time. Will sort out testrunner problem and fix the build.

**Pull request merged**
