### PR TITLE
Pin versions to a known good set

### PR DESCRIPTION
**Pull request by mattss**
I realised that we weren't pinning our versions very well, which may be the cause of unrepeatable test failures in jenkins.

This pins the versions to those I'm currently using, as the tests are passing for me. We'll see what jenkins thinks.

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/16/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/17/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/25/
Test PASSed.

**Comment by mauritsvanrees** [comment]
Very much +1.

I am missing one: `plone.app.blocks = 2.0.0`

And I am inclined to remove all the automatic comments like `# Required by: package x.y`

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/36/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/37/
Test PASSed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/38/
Test PASSed.

**Comment by mattss** [comment]
At the request of @gyst I am breaking this up into hard and soft versions (requirements vs a known good set)

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/40/
Test PASSed.

**Comment by mattss** [comment]
Ok all versions now pinned as far as I can tell, and split into 'versions.cfg' (requirements) and 'soft-versions.cfg' (known good set)

**Pull request merged**
