### PR TITLE
handle pat-switch in workspace sidebar listings, refs #11944

### PR DESCRIPTION
**Pull request by reinhardt**
When the sidebar is expended and I click a document (non-folder) item, the sidebar must contract so that I see the item I clicked. (done with pat-switch, compare prototype)

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Add to whitelist

**Comment by gyst** [comment]
Jenkins test this please test this

**Comment by pilz** [comment]
Jenkins test this please test this

**Comment by pilz** [comment]
Jenkins test this please test this

**Comment by reinhardt** [comment]
Fixed the robot test.

**Comment by reinhardt** [comment]
Jenkins test this please test this
Is that the magic phrase?

**Comment by gyst** [comment]
Looks OK. Jenkins test this please.

**Pull request merged**
