### PR TITLE
Async docconv

### PR DESCRIPTION
**Pull request by pilz**
Generate previews of classic files asynchronously.

### CODE REVIEW

**Comment by pilz** [comment]
please test please

**Comment by pilz** [comment]
the failure is because a demo file is not there, but it is checked in (https://github.com/ploneintranet/ploneintranet/blob/async-docconv/src/ploneintranet/async/tests/test.odt) so I suspect we just need another go. Jenkins please test please

**Comment by gyst** [comment]
Investigating

**Comment by gyst** [comment]
@pilz for me the tests (locally) already break at
https://github.com/ploneintranet/ploneintranet/blob/async-docconv/src/ploneintranet/async/tests/test_tasks.py#L37

I.e. the preview is generated sync, not async, because the async event subscriber eventually delegates to a sync preview generator here:
https://github.com/ploneintranet/ploneintranet/blob/async-docconv/src/ploneintranet/docconv/client/previews.py#L278

Context:
File "/var/tmp/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/var/tmp/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/app/src/ploneintranet/docconv/client/handlers.py", line 48, in content_added_in_workspace
    generate_previews_async(obj)
  File "/app/src/ploneintranet/docconv/client/handlers.py", line 23, in generate_previews_async
    pi_api.previews.generate_previews(obj)
  File "/app/src/ploneintranet/api/previews.py", line 121, in generate_previews
    previews.generate_previews(obj, event)
  File "/app/src/ploneintranet/docconv/client/previews.py", line 279, in generate_previews
    if gsettings.auto_convert:

**Pull request closed without merging**
