### PR TITLE
Updated JS bundle.

### PR DESCRIPTION
**Pull request by jcbrand**
Includes fix for the modal resizing issue.
https://github.com/ploneintranet/ploneintranet.prototype/issues/81

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/148/
Test PASSed.

**Comment by pilz** [comment]
Resizing works, but it calculates the height too small. See screenshots from chrome and safari:
screen shot 2015-06-10 at 16 54 41
screen shot 2015-06-10 at 16 52 49

**Comment by jcbrand** [comment]
@pilz I've updated the bundle again. Could you please take a look again? Thanks.

**Comment by pilz** [comment]
Beautiful, works perfectly now!

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/158/
Test PASSed.

**Pull request merged**
