### PR TITLE
update the markup for events in the sidebar to match the new prototype

### PR DESCRIPTION
**Pull request by pilz**
@gyst Rather small update, but necessary to get the other proto updates for bugfixes in. Otherwise the events sidebar breaks.

### CODE REVIEW

**Comment by pysailor** [comment]
Jenkins test this please

**Comment by pysailor** [comment]
@pilz  Pushed fixes for all 4 failing tests. Lets wait for jenkins...

**Comment by pysailor** [comment]
@pilz Why was it necessary to merge master into this branch? 
Your merge caused a new test failure

**Comment by gyst** [comment]
On 31/08/15 20:42, Wolfgang Thomas wrote:

> @pilz https://github.com/pilz Why was it necessary to merge master
> into this branch?
> Your merge caused a new test failure

Better on the branch now than on master later, not?

## :*CU#

```
Guido Stevens  |  +31.43.3618933  |  http://cosent.nl

s o c i a l   k n o w l e d g e   t e c h n o l o g y
```

**Comment by pilz** [comment]
Because it said it couldn’t automerge anymore after the previous PR was merged. The Diff was somewhat convoluted, but I thought I got it straight forward. Will fix it now.

> Am 31.08.2015 um 20:42 schrieb Wolfgang Thomas notifications@github.com:
> 
> @pilz https://github.com/pilz Why was it necessary to merge master into this branch?
> Your merge caused a new test failure
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ploneintranet/ploneintranet/pull/730#issuecomment-136460296.

## 

Alexander Pilz
SYSLAB.COM GmbH, Landwehrstrasse 60-62, 80336 Munich, Germany
Tel: +49 89 3063589-0 - Fax: +49 89 3063589-9
http://www.syslab.com - Amtsgericht Muenchen, HRB 135057
Steuernummer 143/184/50154 - Ust.-ID: DE212842815

**Pull request merged**
