### PR TITLE
MetroMap: check transition guards for [close milestone]

### PR DESCRIPTION
**Pull request by cillianderoiste**
NOTE: this also sets manager_bypass to False. It's a bit confusing if
the manager can close milestones but other users can't IMO.

### CODE REVIEW

**Comment by gyst** [comment]
What is this supposed to do? On manual testing, I can close milestones with open tasks still in them. I thought the purpose of this would be to prevent that.

**Comment by gyst** [comment]
@cillianderoiste I can close milestones with open tasks in them. Is it not the intent of this pull to prevent that?

**Comment by cillianderoiste** [comment]
@gyst yes, the guard is to prevent someone from closing a milestone when there are still open tasks, but it needs to be configured in a workflow, by assigning the guard to each transition. To enable re-opening milestones we can add extra transitions which don't have guards. We use this in iKath and I thought it might be useful in core PI too. Should I configure it for the Case Workflow?

**Comment by pilz** [comment]
@cillianderoiste Yes. The case workflow in PI is a demo workflow. It's sole purpose is to show how this is intended to work and people will need to customise anyway. So I think it is a good idea to hook that up in the workflow.

**Comment by cillianderoiste** [comment]
@pbauer I've added a gist with an example definition.xml which would need to be adapted to PI: https://gist.github.com/cillianderoiste/95c05550f3bc65c94abb

**Comment by cillianderoiste** [comment]
I've added the transitions which allow milestones to be reopened regardless of the state of tasks.

**Comment by gyst** [comment]
Jenkins please test this

**Comment by gyst** [comment]
Running this branch errors out as soon as I try to load the ploneintranet.suite:testcontent profile.

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 544, in manage_importAllSteps
  Module Products.GenericSetup.tool, line 365, in runAllImportStepsFromProfile
- **traceback_info**: profile-ploneintranet.suite:testing
  Module Products.GenericSetup.tool, line 1184, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1095, in _doRunImportStep
- **traceback_info**: ploneintranet.testing
  Module ploneintranet.suite.setuphandlers, line 75, in testing
  Module ploneintranet.suite.setuphandlers, line 504, in create_caseworkspaces
  Module ploneintranet.suite.setuphandlers, line 517, in create_ws_content
  Module plone.api.content, line 2, in create
  Module plone.api.validation, line 70, in wrapped
  Module plone.api.content, line 2, in create
  Module plone.api.validation, line 131, in wrapped
  Module plone.api.content, line 78, in create
  Module plone.dexterity.content, line 745, in invokeFactory
  Module Products.CMFCore.PortalFolder, line 292, in invokeFactory
  Module Products.CMFCore.TypesTool, line 833, in constructContent
  Module Products.CMFCore.TypesTool, line 311, in constructInstance
  Module Products.CMFCore.TypesTool, line 569, in _constructInstance
  Module Products.BTreeFolder2.BTreeFolder2, line 455, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module ploneintranet.workspace.subscribers, line 207, in update_todo_state
  Module ploneintranet.todo.content.todo, line 59, in set_appropriate_state
  Module ploneintranet.todo.content.todo, line 40, in reopen
  Module ploneintranet.workspace.adapters, line 277, in metromap_sequence
  Module Products.CMFPlone.WorkflowTool, line 95, in getTransitionsFor
  Module Products.DCWorkflow.DCWorkflow, line 398, in _checkTransitionGuard
  Module Products.DCWorkflow.Guard, line 89, in check
  Module Products.CMFCore.Expression, line 47, in __call__
  Module zope.tales.expressions, line 217, in **call**
  Module Products.PageTemplates.Expressions, line 147, in _eval
  Module zope.tales.expressions, line 124, in _eval
  Module Products.PageTemplates.Expressions, line 74, in boboAwareZopeTraverse
  Module OFS.Traversable, line 317, in restrictedTraverse
  Module OFS.Traversable, line 300, in unrestrictedTraverse
- **traceback_info**: ([], 'case_workflow_guard')
  KeyError: 'case_workflow_guard'

**Comment by gyst** [comment]
I will work on #758 and #517 and #462 today.

**Comment by pilz** [comment]
@gyst please check with @cillianderoiste what he might already have available in the case-manager brand. There is potential for work duplication.

**Comment by gyst** [comment]
Superseded by #773, closing.

**Pull request closed without merging**
