### PR TITLE
Fix robot login keyword

### PR DESCRIPTION
**Pull request by mattss**
Previously this did a GET, breaking CSRF protection

### CODE REVIEW

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/23/
Test FAILed.

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/24/
Test FAILed.

**Comment by mattss** [comment]
Retest this please jenkins

**Comment by ghost** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.ploneintranet.net/job/Plone.Intranet.Pull.Request.Builder/29/
Test PASSed.

**Pull request merged**
