### PR TITLE
Workspace sorting

### PR DESCRIPTION
**Pull request by ckirchhoff**
Added a dropdown to sort workspaces. The available options are: alphabetical, newest and most active. 'Alphabetical' is default and 'most active' is not yet implemented. Choosing the latter throws a NotImplementedError.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by gyst** [comment]
Jenkins please test this

**Comment by gyst** [comment]
Please test this

**Comment by gyst** [comment]
please test this please

**Comment by gyst** [comment]
No user exposed UI should ever trigger a traceback. If it's not implemented, disable that UI option.

**Comment by pilz** [comment]
please test this please retest this

**Comment by pilz** [comment]
please test this please retest this

**Pull request merged**
